#
# Copyright (C) 2021-2022 The LineageOS Project
#
# SPDX-License-Identifier: Apache-2.0
#

# Include the common OEM chipset BoardConfig.
include device/oneplus/sm8350-common/BoardConfigCommon.mk

DEVICE_PATH := device/oneplus/lemonadep

# Version and security patch level
PLATFORM_SECURITY_PATCH := 2026-07-01
VENDOR_SECURITY_PATCH := 2025-04-01
BOOT_SECURITY_PATCH := $(PLATFORM_SECURITY_PATCH)
PLATFORM_VERSION := 16
PLATFORM_VERSION_LAST_STABLE := $(PLATFORM_VERSION)

# Properties
TARGET_VENDOR_PROP += $(DEVICE_PATH)/vendor.prop


# HIDL
#DEVICE_MANIFEST_FILE += $(DEVICE_PATH)/manifest.xml

# Recovery
TARGET_SCREEN_DENSITY := 420
TARGET_RECOVERY_DENSITY := xxhdpi
TARGET_RECOVERY_UI_MARGIN_HEIGHT := 126

#NEED_KERNEL_MODULE_RECOVERY := true

# Build broken checks
BUILD_BROKEN_MISSING_REQUIRED_MODULES := true
BUILD_BROKEN_ARTIFACT_PATH_REQUIREMENTS := true

### NEW

#TARGET_NO_RECOVERY := true
BOARD_EXCLUDE_KERNEL_FROM_RECOVERY_IMAGE := true
ALLOW_MISSING_DEPENDENCIES := true


